//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace codeweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserOrder()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public string IDOrder { get; set; }
        public System.DateTime TimeOrder { get; set; }
        public int TotalQuantity { get; set; }
        public string OrderStatus { get; set; }
        public decimal TotalMoney { get; set; }
        public string OrderAddress { get; set; }
        public string PhoneNum { get; set; }
        public string CustomerID { get; set; }
        public int IDStaff { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
